Fix CI not setting the job as failed when connector validation finds violations

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,6 +47,13 @@ jobs:
         run: |
           source ./.venv/bin/activate
           python -m connector_packager.package --validate-only $GITHUB_WORKSPACE/cratedb-tableau-connector/cratedb_jdbc
+          
+          cat packaging_logs.txt
+          
+          # If validation fails, stop the job.
+          if grep 'validation failed' packaging_logs.txt; then
+            exit 1
+          fi
 
       - name: Build connector
         if: ${{ github.event_name == 'release' }}
